name: Release

on:
  push:
    tags:
      - '*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set version
        run: |
          sed -i "s/version.*=.*/version = \"${GITHUB_REF##*/}\"/g" Cargo.toml
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Publish
        run: cargo publish --allow-dirty --token ${CARGO_CRATES_TOKEN}
        env:
          CARGO_CRATES_TOKEN: ${{ secrets.CARGO_CRATES_TOKEN }}
